drop table if exists tb_specialty CASCADE 

create table tb_specialty (
     id bigint generated by default as identity,
     deleted boolean not null,
     name varchar(255),
     primary key (id)
    )
    
drop table if exists tb_specialty CASCADE 
