 drop table if exists tb_role CASCADE 
 
create table tb_role (
    id bigint generated by default as identity,
    authority varchar(255),
    primary key (id)
    )

drop table if exists tb_role CASCADE 